%% Add yalmip (parser) and mosek (solver) to path

p = ['./mosek/8/toolbox/r2014a:', ...
     './yalmip:', ...
     './yalmip/demos:', ...
     './yalmip/extras:', ...
     './yalmip/modules:', ...
     './yalmip/modules/bilevel:', ...
     './yalmip/modules/global:', ...
     './yalmip/modules/moment:', ...
     './yalmip/modules/parametric:', ...
     './yalmip/modules/robust:', ...
     './yalmip/modules/sos:', ...
     './yalmip/operators:', ...
     './yalmip/solvers:'
];
path(p,path);
clear p;
clear path;
